# 1. Script to match the output "how are you ?"
print('how are you ?')

# 2. Script to match the output "I ate 412 jelly beans."
jelly_beans = input("Enter the number of jelly beans you ate: ")
jelly_beans = int(jelly_beans)
print("I ate", jelly_beans, "jelly beans.")

# 3. Script to match the output "The number of times I have seen 'The Force Awakens' is 104"
number_of_times = 104
print("The number of times I have seen 'The Force Awakens' is", number_of_times)

# 4. Script to perform addition with variables and display the result
number_1 = 7
number_2 = 9
result = number_1 + number_2
print("The answer is", result)

# 5. Script to perform subtraction with variables and display the result
number_1 = 21
number_2 = 7
result = number_1 - number_2
print("The answer is", result)

# 6. Script to perform division with the `/` and `//` operators
number_1 = 17
number_2 = 4
result_division = number_1 / number_2
result_integer_division = number_1 // number_2
print(result_division)
print(result_integer_division)

# 7. Script to perform multiplication with variables and display the result
number_1 = 6
number_2 = 38
result = number_1 * number_2
print("The answer is", result)

# 8. Script to match the output "The remainder when 72 is divided by 19 is 15"
number_1 = 72
number_2 = 19
remainder = number_1 % number_2
print("The remainder when", number_1, "is divided by", number_2, "is", remainder)

# 9. Script to match the output "The answer is 16"
number_1 = 10
number_2 = 6
result = number_1 + number_2
print("The answer is", result)

# 10. Script to adjust the equation with parentheses
my_calculation = (6 + (7 / (4 - 2)))
print(my_calculation)

# 11. Script to get and display a number using input
jelly_beans = input("Enter the number of jelly beans you ate: ")
jelly_beans = int(jelly_beans)
print("I ate", jelly_beans, "jelly beans.")
